version: '3.9'

services:
  flaskapp:
    image: flasktemplate:latest
    build: .
    volumes:
      - flaskapp-data:/var/runtime/logs
    depends_on:
      - redis
      - mysql
    restart: always
    ports:
      - 5000:5000
  redis:
    image: redis:latest
    build: db/redis
    restart: always
    volumes:
      - redis-data:/data
    command: redis-server /etc/redis/redis.conf
    ports:
      - 6379:6379
  mysql:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test:
        [ "CMD","mysqladmin","ping","-h","127.0.0.1","--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - db-password
    environment:
      - MYSQL_DATABASE=flasktemplate
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
  APIProxy:
    image: apiproxy:latest
    build: nginx/APIProxy
    volumes:
      - nginx-api-data:/var/log/nginx
    restart: always
    ports:
      - 5100:80
    depends_on:
      - flaskapp
  StaticProxy:
    image: staticproxy:latest
    build: nginx/StaticProxy
    volumes:
      - nginx-static-data:/var/log/nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - APIProxy
volumes:
  flaskapp-data:
  mysql-data:
  redis-data:
  nginx-api-data:
  nginx-static-data:
secrets:
  db-password:
    file: db/mysql/password.txt
